name: superheroes
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  provider: ^6.1.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  network_image_mock: ^2.1.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - .env
